[package]
name = "mon-gm"
version = "0.1.0"
authors = ["TheSpiritXIII <thespiritxiii@gmail.com>"]

[lib]
name = "mon_gm"
crate-type = ["cdylib"]

[dependencies.mon-gen-c]
path = "../mon-gen-c"
version = "0.1.0"

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'
