[package]
name = "mon-cli"
version = "0.1.0"
authors = ["TheSpiritXIII <thespiritxiii@gmail.com>"]

[dependencies.mon-gen]
path = "../mon-gen"
version = "0.4.0"
features = ["test"]

[dependencies]
rand = "0.3"
