[species]
name = "Bulbasaur"
id = 0
description = "Bulbasaur can be seen napping in bright sunlight. There is a seed on its back. By soaking up the sun's rays, the seed grows progressively larger."
kind = "Seed"
elements = ["Grass", "Poison"]
gender = "SevenMaleToOne"
experience = 64
height = 0.7
weight = 6.9
rareness = 45
friendship = 70
hatch = 20
groups = ["Monster", "Grass"]
growth = "MediumSlow"
color = "Green"
habitat = "Grassland"

[species.abilities]
default = ["Overgrow"]
hidden = ["Chlorophyll"]

[species.statistics]
base = { health = 45, attack = 49, defense = 49, sp-attack = 45, sp-defense = 65, speed = 65 }
yield = { sp-defense = 1 }

[species.attacks]
learnable = [
	{ level = 1, attacks = ["Tackle"] },
	{ level = 3, attacks = ["Growl"] },
	# { level = 7, attacks = ["Leechseed"] },
	# { level = 9, attacks = ["Vinewhip"] },
	# { level = 13, attacks = ["PoisonPower", "SleepPowder"] },
	# { level = 15, attacks = ["Takedown"] },
	# { level = 19, attacks = ["Razorleaf"] },
	# { level = 21, attacks = ["Sweetscent"] },
	# { level = 25, attacks = ["Growth"] },
	# { level = 27, attacks = ["DoubleEdge"] },
	# { level = 31, attacks = ["WorrySeed"] },
	# { level = 33, attacks = ["Synthesis"] },
	# { level = 37, attacks = ["SeedBomb"] }
]
inheritable = [
	# "Amnesia",
	# "Charm",
	# "Curse",
	# "Endure",
	# "Gigadrain",
	# "Grasswhistle",
	# "Ingrain",
	# "Leafstorm",
	# "MagicLeaf",
	# "NaturePower",
	# "PetalDance",
	# "PowerWhip",
	# "SkullBash",
	# "Sludge"
]
teachable = [
	# "Attract",
	# "Bind",
	# "Confide",
	# "Cut",
	# "DoubleTeam",
	# "EchoedVoice",
	# "EnergyBall",
	# "Facade",
	# "Flash",
	# "Frustration",
	# "GigaDrain",
	# "GrassKnot",
	# "GrassPledge",
	# "HiddenPower",
	# "KnockOff",
	# "LightScreen",
	# "NaturePower",
	# "Protect",
	# "Rest",
	# "Return",
	# "RockSmash",
	# "Round",
	# "Safeguard",
	# "SecretPower",
	# "SeedBomb",
	# "SleepTalk",
	# "SludgeBomb",
	# "Snore",
	# "SolarBeam",
	# "Strength",
	# "Substitute",
	# "SunnyDay",
	# "Swagger",
	# "SwordsDance",
	# "Synthesis",
	# "Toxic",
	# "Venoshock",
	# "WorrySeed"
]
