[species]
name = "Mew"
id = 4
description = "Mew is said to possess the genetic composition of all Pokémon. It is capable of making itself invisible at will, so it entirely avoids notice even if it approaches people."
kind = "New Species"
elements = ["Psychic"]
gender = "Genderless"
experience = 64
height = 0.4
weight = 4.0
rareness = 45
friendship = 100
hatch = 120
groups = ["Undiscovered"]
growth = "MediumSlow"
color = "Pink"
habitat = "Rare"

[species.abilities]
default = ["Synchronize"]

[species.statistics]
base = { health = 100, attack = 100, defense = 100, sp-attack = 100, sp-defense = 100, speed = 100 }
yield = { health = 3 }

[species.attacks]
learnable = [
	{ level = 1, attacks = ["Pound"] }
	# { level = 1, attacks = ["ReflectType", "Transform"] },
	# { level = 10, attacks = ["MegaPunch"] },
	# { level = 20, attacks = ["Metronome"] },
	# { level = 30, attacks = ["Psychic"] },
	# { level = 40, attacks = ["Barrier"] },
	# { level = 50, attacks = ["AncientPower"] },
	# { level = 60, attacks = ["Amnesia"] },
	# { level = 70, attacks = ["MeFirst"] },
	# { level = 80, attacks = ["BatonPass"] },
	# { level = 90, attacks = ["NastyPlot"] },
	# { level = 100, attacks = ["AuraSphere"] }
]
teachable = [
	# "Acrobatics",
	# "AerialAce",
	# "AfterYou",
	# "AquaTail",
	# "Attract",
	# "Bind",
	# "Blizzard",
	# "Block",
	# "Bounce",
	# "BrickBreak",
	# "BugBite",
	# "BulkUp",
	# "Bulldoze",
	# "CalmMind",
	# "ChargeBeam",
	# "Confide",
	# "Covet",
	# "Cut",
	# "DarkPulse",
	# "DazzlingGleam",
	# "Dig",
	# "Dive",
	# "DoubleTeam",
	# "DragonClaw",
	# "DragonPulse",
	# "DragonTail",
	# "DrainPunch",
	# "DreamEater",
	# "DrillRun",
	# "DualChop",
	# "EarthPower",
	# "Earthquake",
	# "EchoedVoice",
	# "Electroweb",
	# "Embargo",
	# "Endeavor",
	# "EnergyBall",
	# "Explosion",
	# "Facade",
	# "FalseSwipe",
	# "FireBlast",
	# "FirePunch",
	"Fissure",
	# "FlameCharge",
	# "Flamethrower",
	# "Flash",
	# "FlashCannon",
	# "Fling",
	# "Fly",
	# "FocusBlast",
	# "FocusPunch",
	# "FoulPlay",
	# "FrostBreath",
	# "Frustration",
	# "GastroAcid",
	# "GigaDrain",
	# "GigaImpact",
	# "GrassKnot",
	# "Gravity",
	# "GunkShot",
	# "GyroBall",
	# "Hail",
	# "HealBell",
	# "HeatWave",
	# "HelpingHand",
	# "HiddenPower",
	# "HoneClaws",
	# "HyperBeam",
	# "HyperVoice",
	# "IceBeam",
	# "IcePunch",
	# "IcyWind", 
	# "Incinerate",
	# "Infestation",
	# "IronDefense",
	# "IronHead",
	# "IronTail",
	# "KnockOff",
	# "LastResort",
	# "LightScreen",
	# "LowKick",
	# "LowSweep",
	# "MagicCoat",
	# "MagicRoom",
	# "MagnetRise",
	# "NaturePower",
	# "Outrage",
	# "Overheat",
	# "PainSplit",
	# "Payback",
	# "PoisonJab",
	# "PowerUpPunch",
	# "Protect",
	# "Psychic",
	# "PsychUp",
	# "Psyshock",
	# "Quash",
	# "RainDance",
	# "Recycle",
	# "Reflect",
	# "Rest",
	# "Retaliate",
	# "Return",
	# "Roar",
	# "RockPolish",
	# "RockSlide",
	# "RockSmash",
	# "RockTomb",
	# "RolePlay",
	# "Roost",
	# "Round",
	# "Safeguard",
	# "Sandstorm",
	# "Scald",
	# "SecretPower",
	# "SeedBomb",
	# "ShadowBall",
	# "ShadowClaw",
	# "ShockWave",
	# "SignalBeam",
	# "SkillSwap",
	# "SkyAttack",
	# "SkyDrop",
	# "SleepTalk",
	# "SludgeBomb",
	# "SludgeWave",
	# "SmackDown",
	# "Snarl",
	# "Snatch",
	# "Snore",
	# "SolarBeam",
	"Splash",
	# "Spite",
	# "StealthRock",
	# "SteelWing",
	# "StoneEdge",
	# "Strength",
	# "StruggleBug",
	# "Substitute",
	# "SunnyDay",
	# "SuperFang",
	# "Superpower",
	"Surf",
	# "Swagger",
	# "SwordsDance",
	# "Synthesis",
	# "Tailwind",
	# "Taunt",
	# "Thief",
	# "Thunder",
	# "Thunderbolt",
	# "ThunderPunch",
	# "ThunderWave",
	# "Torment",
	# "Toxic",
	# "Trick",
	"TrickRoom",
	"Uturn"
	# "Uproar",
	# "Venoshock",
	# "VoltSwitch",
	# "Waterfall",
	# "WaterPulse",
	# "WildCharge",
	# "WillOWisp",
	# "WonderRoom",
	# "WorrySeed",
	# "XScissor",
	# "ZenHeadbutt"
]
