[species]
name = "Deoxys"
id = 4
description = "An alien virus that fell to earth on a meteor underwent a DNA mutation to become this Pokémon."
kind = "DNA"
forms = [
	{ name = "Normal Forme",  id = 0, internal = "Normal" },
	{ name = "Attack Forme",  id = 1, internal = "Attack" },
	{ name = "Defense Forme", id = 2, internal = "Defense" },
	{ name = "Speed Forme",   id = 3, internal = "Speed" }
]
elements = ["Psychic"]
gender = "Genderless"
experience = 270
height = 1.7
weight = 60.8
rareness = 3
friendship = 0
hatch = 121
groups = ["Undiscovered"]
growth = "Slow"
color = "Red"
habitat = "Rare"

[species.abilities]
default = ["Pressure"]

[species.statistics]
base = [
	{ form = "Normal",  health = 50, attack = 150, defense = 50,  sp-attack = 150, sp-defense = 50, speed = 150},
	{ form = "Attack",  health = 50, attack = 180, defense = 20,  sp-attack = 180, sp-defense = 20, speed = 150},
	{ form = "Defense", health = 50, attack = 70,  defense = 160, sp-attack = 70,  sp-defense = 160, speed = 90},
	{ form = "Speed",   health = 50, attack = 95,  defense = 90,  sp-attack = 95,  sp-defense = 90, speed = 180}
]
yield = [
	{ form = "Normal",  attack = 1, sp-attack = 1, speed = 1 },
	{ form = "Attack",  attack = 2, sp-attack = 1 },
	{ form = "Defense", defense = 2, sp-defense = 1 },
	{ form = "Speed",   speed = 3}
]

[species.attacks]
learnable = [
	{ level = 1, attacks = ["Pound"] } # TODO: This attack is not actually learnable.
	# { level = 1,  attacks = ["Leer", "Wrap"] },
	# { level = 7,  attacks = ["NightShade"] },
	# { level = 13, attacks = [
	# 	{ attacks = ["Teleport"] },
	# 	{ form = "Speed", attacks = ["DoubleTeam"] }
	# ]},
	# { level = 19, attacks = [
	# 	{ attacks = ["Knockoff"] },
	# 	{ form = "Attack", attacks = ["Taunt"] }
	# ]},
	# { level = 25, attacks = [
	# 	{ attacks = ["Pursuit"] },
	# 	{ form = "Defense", attacks = ["Spikes"] }
	# ]},
	# { level = 31, attacks = ["Psychic"] },
	# { level = 37, attacks = [
	# 	{ attacks = ["Snatch"] },
	# 	{ form = "Attack", attacks = ["Superpower"] },
	# 	{ form = "Speed", attacks = ["Swift"] }
	# ]},
	# { level = 43, attacks = ["PsychoShift"] },
	# { level = 49, attacks = ["ZenHeadbutt"] },
	# { level = 55, attacks = [
	# 	{ attacks = ["CosmicPower"] },
	# 	{ form = "Defense", attacks = ["IronDefense", "Amnesia"] },
	# 	{ form = "Speed", attacks = ["Agility"] }
	# ]},
	# { level = 61, attacks = [
	# 	{ attacks = ["Recover"] },
	# 	{ form = "Attack", attacks = ["ZapCannon"] }
	# ]},
	# { level = 67, attacks = ["PsychoBoost"] },
	# { level = 73, attacks = [
	# 	{ attacks = ["HyperBeam"] },
	# 	{ form = "Defense", attacks = ["Counter", "MirrorCoat"] },
	# 	{ form = "Speed", attacks = ["ExtremeSpeed"] }
	# ]}
]
