[attack]
name = "Vine Whip"
internal = "VineWhip"
id = 2
description = "The target is struck with slender, whiplike vines to inflict damage."
element = "Grass"
category = "Physical"
power = 45
accuracy = 1.0
limit = 25
