[attack]
name = "Sand Attack"
internal = "SandAttack"
id = 3
description = "Sand is hurled in the target's face, reducing the target's accuracy."
element = "Ground"
category = "Status"
accuracy = 1.0
limit = 15
effect = "miss_or(data, |data| { modifier::accuracy::delta(data, -1) })"
