[attack]
name = "Fissure"
id = 9
description = "The user opens up a fissure in the ground and drops the target in. The target faints instantly if this attack hits."
element = "Ground"
category = "Physical"
limit = 5
effect = "miss_or(data, |data| { knock_out(data) })" # TODO: Separate miss calculation.
