[attack]
name = "Knock Off"
id = 2
internal = "KnockOff"
description = "The user slaps down the target’s held item, and that item can’t be used in that battle. The move does more damage if the target has a held item."
element = "Dark"
category = "Physical"
power = 65
accuracy = 1.0
limit = 20
