[attack]
name = "U-turn"
internal = "Uturn"
id = 3
description = "After making its attack, the user rushes back to switch places with a party Pokémon in waiting."
element = "Bug"
category = "Physical"
power = 70
accuracy = 1.0
limit = 20
effect = "damage_retreat"
