[attack]
name = "Trick Room"
internal = "TrickRoom"
id = 3
description = "The user creates a bizarre area in which slower Pokémon get to move first for five turns."
element = "Psychic"
category = "Status"
limit = 5
effect = "battle_speed_reverse"
