[[classifier]]
name = "growth"
type = "u8"
values = [
	{name = "Flunctuating", id = 0},
	{name = "Slow",         id = 1},
	{name = "MediumSlow",   id = 2},
	{name = "MediumFast",   id = 3},
	{name = "Fast",         id = 4},
	{name = "Erratic",      id = 5}
]

[[classifier]]
name = "group"
type = "u8"
max = 2
values = [
	{name = "Undiscovered", id = 0},
	{name = "Monster",      id = 1},
	{name = "Water1",       id = 2},
	{name = "Bug",          id = 3},
	{name = "Flying",       id = 4},
	{name = "Field",        id = 5},
	{name = "Fairy",        id = 6},
	{name = "Grass",        id = 7},
	{name = "Human",        id = 8},
	{name = "Mineral",      id = 9},
	{name = "Amorphous",    id = 10},
	{name = "Water2",       id = 11},
	{name = "Ditto",        id = 12},
	{name = "Dragon",       id = 13}
]

volatile = [
	{name = "BadPoison",     id = 1},
	{name = "Confusion",     id = 2},
	{name = "Curse",         id = 4},
	{name = "Embargo",       id = 8},
	{name = "Encore",        id = 16},
	{name = "Flinch",        id = 32},
	{name = "HealBlock",     id = 64},
	{name = "Idenficiation", id = 128},
	{name = "Nightmare",     id = 256},
	{name = "PerishSong",    id = 512},
	{name = "Seed",          id = 1024},
	{name = "Levitation",    id = 2048},
	{name = "Torment",       id = 4096},
	{name = "TrapPartial",   id = 8192},
	{name = "TrapFull",      id = 16384}
]
battle = [
	{name = "AquaRing",     id = 1},
	{name = "Brace",        id = 2},
	{name = "DefenseCurl",  id = 4},
	{name = "Glowing",      id = 8},
	{name = "Rooting",      id = 16},
	{name = "MagicCoat",    id = 32},
	{name = "Leviation",    id = 64},
	{name = "Protection",   id = 128},
	{name = "Recharge",     id = 256},
	{name = "Invulnerable", id = 512},
	{name = "Substitute",   id = 1024},
	{name = "Aim",          id = 2048},
	{name = "Sunlight",     id = 4096},
	{name = "Withdraw",     id = 8192},
	{name = "Whirlwind",    id = 16384}
]
