[classifiers]
natures = [
	{name = "Hardy",   id = 0},
	{name = "Lonely",  id = 1},
	{name = "Brave",   id = 2},
	{name = "Adamant", id = 3},
	{name = "Naughty", id = 4},
	{name = "Bold",    id = 5},
	{name = "Docile",  id = 6},
	{name = "Relaxed", id = 7},
	{name = "Impish",  id = 8},
	{name = "Lax",     id = 9},
	{name = "Timid",   id = 10},
	{name = "Hasty",   id = 11},
	{name = "Serious", id = 12},
	{name = "Jolly",   id = 13},
	{name = "Naive",   id = 14},
	{name = "Modest",  id = 15},
	{name = "Mild",    id = 16},
	{name = "Quiet",   id = 17},
	{name = "Bashful", id = 18},
	{name = "Rash",    id = 19},
	{name = "Calm",    id = 20},
	{name = "Gentle",  id = 21},
	{name = "Sassy",   id = 22},
	{name = "Careful", id = 23},
	{name = "Quirky",  id = 24}
]
growth = [
	{name = "Fluctuating", id = 0},
	{name = "Slow",         id = 1},
	{name = "MediumSlow",   id = 2},
	{name = "MediumFast",   id = 3},
	{name = "Fast",         id = 4},
	{name = "Erratic",      id = 5}
]
groups = [
	{name = "Undiscovered", id = 0},
	{name = "Monster",      id = 1},
	{name = "Water1",       id = 2},
	{name = "Bug",          id = 3},
	{name = "Flying",       id = 4},
	{name = "Field",        id = 5},
	{name = "Fairy",        id = 6},
	{name = "Grass",        id = 7},
	{name = "Human",        id = 8},
	{name = "Water3",       id = 9},
	{name = "Mineral",      id = 10},
	{name = "Amorphous",    id = 11},
	{name = "Water2",       id = 12},
	{name = "Ditto",        id = 13},
	{name = "Dragon",       id = 14}
]
colors = [
	{name = "Red",    id = 0},
	{name = "Blue",   id = 1},
	{name = "Yellow", id = 2},
	{name = "Green",  id = 3},
	{name = "Black",  id = 4},
	{name = "Brown",  id = 5},
	{name = "Purple", id = 6},
	{name = "Gray",   id = 7},
	{name = "White",  id = 8},
	{name = "Pink",    id = 9}
]
habitats = [
	{name = "Grassland",    id = 0},
	{name = "Forest",       id = 1},
	{name = "WatersEdge",   id = 2},
	{name = "Sea",          id = 3},
	{name = "Cave",         id = 4},
	{name = "Mountain",     id = 5},
	{name = "RoughTerrain", id = 6},
	{name = "Urban",        id = 7},
	{name = "Rare",         id = 8}
]

[classifiers.ailments]
nonvolatile = [
	{name = "Burn",      id = 0},
	{name = "Freeze",    id = 1},
	{name = "Paralysis", id = 2},
	{name = "Poison",    id = 3},
	{name = "Sleep",     id = 4}
]
