natures = [
	{ name = "Hardy",   id = 0 },
	{ name = "Lonely",  id = 1 },
	{ name = "Brave",   id = 2 },
	{ name = "Adamant", id = 3 },
	{ name = "Naughty", id = 4 },
	{ name = "Bold",    id = 5 },
	{ name = "Docile",  id = 6 },
	{ name = "Relaxed", id = 7 },
	{ name = "Impish",  id = 8 },
	{ name = "Lax",     id = 9 },
	{ name = "Timid",   id = 10 },
	{ name = "Hasty",   id = 11 },
	{ name = "Serious", id = 12 },
	{ name = "Jolly",   id = 13 },
	{ name = "Naive",   id = 14 },
	{ name = "Modest",  id = 15 },
	{ name = "Mild",    id = 16 },
	{ name = "Quiet",   id = 17 },
	{ name = "Bashful", id = 18 },
	{ name = "Rash",    id = 19 },
	{ name = "Calm",    id = 20 },
	{ name = "Gentle",  id = 21 },
	{ name = "Sassy",   id = 22 },
	{ name = "Careful", id = 23 },
	{ name = "Quirky",  id = 24 },
]

catch-methods = [
	{ name = "Uncaught",    id = 0 },
	{ name = "PokeBall",    id = 1 },
	{ name = "GreatBall",   id = 2, rate = 1.5 },
	{ name = "UltraBall",   id = 3, rate = 2.0 },
	{ name = "MasterBall",  id = 4, rate = 255.0 },
	{ name = "SafariBall",  id = 4, rate = 1.5 },
	{ name = "LevelBall",   id = 5 },
	{ name = "LureBall",    id = 6 },
	{ name = "MoonBall",    id = 7 },
	{ name = "FriendBall",  id = 8 },
	{ name = "LoveBall",    id = 9 },
	{ name = "HeavyBall",   id = 10 },
	{ name = "FastBall",    id = 11 },
	{ name = "SportBall",   id = 12 },
	{ name = "PremierBall", id = 13 },
	{ name = "RepeatBall",  id = 14 },
	{ name = "TimerBall",   id = 15 },
	{ name = "NestBall",    id = 16 },
	{ name = "NetBall",     id = 17 },
	{ name = "DiveBall",    id = 18 },
	{ name = "LuxuryBall",  id = 19 },
	{ name = "HealBall",    id = 20 },
	{ name = "QuickBall",   id = 21 },
	{ name = "DuskBall",    id = 22 },
	{ name = "CherishBall", id = 23 },
	{ name = "ParkBall",    id = 24 },
	{ name = "DreamBall",   id = 25 },
]
